from selenium.webdriver.common.by import By

class CheckoutCartLocators:
    CHECKOUT_BUTTON = (By.XPATH, "//a[contains(@class, 'btn') and contains(text(), 'Checkout')]")
    INPUT_REGISTER_ACCOUNT = (By.XPATH, "//input[@value='register']")
    NEW_CUSTOMER_BUTTON_CONTINUE = (By.XPATH, "//input[@id='button-account']")
    INPUT_FIRST_NAME = (By.XPATH, "//input[@id='input-payment-firstname']")
    INPUT_LAST_NAME = (By.XPATH, "//input[@id='input-payment-lastname']")
    INPUT_EMAIL = (By.XPATH, "//input[@id='input-payment-email']")
    INPUT_TELEPHONE = (By.XPATH, "//input[@id='input-payment-telephone']")
    INPUT_SHIPPING_ADDRESS1 = (By.XPATH, "//input[@id='input-payment-address-1']")
    INPUT_SHIPPING_CITY = (By.XPATH, "//input[@id='input-payment-city']")
    INPUT_SHIPPING_POSTCODE = (By.XPATH, "//input[@id='input-payment-postcode']")
    SELECT_INPUT_SHIPPING_COUNTY = (By.XPATH, "//select[@id='input-payment-country']")
    OPTION_SHIPPING_COUNTY = (By.XPATH, "//option[@value='9' and contains(text(), 'Antigua and Barbuda')]")
    SELECT_INPUT_SHIPPING_REGION = (By.XPATH, "//select[@id='input-payment-zone']")
    OPTION_SHIPPING_REGION = (By.XPATH, "//option[@value='153' and contains(text(), 'Barbuda')]")
    INPUT_PASSWORD = (By.XPATH, "//input[@id='input-payment-password']")
    INPUT_PASSWORD_CONFIRM = (By.XPATH, "//input[@id='input-payment-confirm']")
    INPUT_REGISTER_AGREE = (By.XPATH, "//input[@name='agree']")
    CONTINUE_BUTTON = (By.XPATH, "//input[@id='button-register']")
    MY_ACCOUNT_LINK_DROPDOWN = (By.XPATH, "//a[@title='My Account']")
    FORM_CHECK_LABEL = (By.XPATH, "//div[@id='payment-existing']")
    MY_ACCOUNT_LINK = (By.XPATH, "//a[contains(text(), 'My Account')]")
    REMOVE_PALM_BUTTON = (By.XPATH, "//a[text()='Palm Treo Pro']/ancestor::tr//button[contains(@data-original-title, 'Remove')]")
    INPUT_QUANTITY_IPHONE = (By.XPATH, "//a[text()='iPhone']/ancestor::tr//input[@class='form-control']")
    UPDATE_BUTTON = (By.XPATH, "//button[@data-original-title='Update']")
    ESTIMATE_SHIPPIN_LINK = (By.XPATH, "//a[@class='accordion-toggle' and contains(text(), 'Estimate Shipping & Taxes ')]")
    SELECT_ESTIMATE_COUNTRY = (By.XPATH, "//select[@id='input-country']")
    SELECT_ESTIMATE_REGION = (By.XPATH, "//select[@id='input-zone']")
    INPUT_ESTIMATE_POSTCODE = (By.XPATH, "//input[@id='input-postcode']")
    GET_QUOTES_BUTTON = (By.XPATH, "//button[@id='button-quote']")
    CANCEL_MODAL_BUTTON = (By.XPATH, "//button[text()='Cancel']")
    CHECKBOX_USE_EXISTING_ADDRESS = (By.XPATH, "//input[@type='radio' and @name='payment_address' and @value='existing']")
    CONTINUE_BUTTON_PAYMENT_ADDRESS = (By.XPATH, "//input[@id='button-payment-address']")
    CHECKBOX_USE_EXISTING_SHIPPING_ADDRESS = (By.XPATH, "//input[@type='radio' and @name='shipping_address' and @value='existing']")
    CONTINUE_BUTTON_SHIPPING_ADDRESS = (By.XPATH, "//input[@id='button-shipping-address']")
    COMMENT_TEXTAREA = (By.XPATH, "//textarea[@name='comment']")
    CONTINUE_BUTTON_SHIPPING_METHOD = (By.XPATH, "//input[@id='button-shipping-method']")
    CONTINUE_BUTTON_PAYMENT_METHOD = (By.XPATH, "//input[@id='button-payment-method']")
    CONFIRM_ORDER_BUTTON = (By.XPATH, "//input[@id='button-confirm']")
